# This action releases orsopy on PyPI for every version tagged commit (e.g. v0.0.1)

name: PyPI Release

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-setuptools python3-pip python3-yaml
    - name: Build PyPI package
      run: |
        pip3 install build
        python3 -m build
    - name: Archive files
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-20-dist
        path: |
          dist/orsopy*.whl
          dist/orsopy*.tar.gz
